# Generated by Django 5.0.6 on 2024-05-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_name_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="None", max_length=255),
        ),
    ]
