---
name: Checks

on: [push]

jobs: 
  test-lint:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Login into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERGHUB_USER }}
          password: ${{ secrets.DOCKERGHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"